version: '3.1'
services:
  sistemaDiretordb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sistemaDiretor
    volumes:
      - sdbd:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sdbd:
    driver: local



